### PR TITLE
Working on #387.  Adding entries from https://en.wikipedia.org/wiki/L…

### PR DESCRIPTION
**Pull request by eliotpearson**
Pulled the latest year of deceased congressman and added them based off of:

https://en.wikipedia.org/wiki/List_of_members_of_the_United_States_House_of_Representatives_who_died_in_2016

### CODE REVIEW

**Comment by JoshData** [comment]
Cool. I think `died` would be a better key name. Also need to document the new field in the README.

**Comment by eliotpearson** [comment]
@JoshData thanks for the quick PR review.  How about this?

**Comment by JoshData** [comment]
So now the question is, how do we get this info for all of the deaths Wikipedia has?

House: 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016
Senate: 1910s 1920s 1930s 1940s 1950s 1960s 1970s 1980s 1990s 2000s 2010s

A scrape of bioguide.congress.gov might be more effective, since we could get every death date in one shot. See https://github.com/unitedstates/congress-legislators/blob/bioguide-deep-parse/scripts/bioguide.py for some work I did on that. It might already be able to do it.

**Comment by eliotpearson** [comment]
Unfortunately I do not have bandwidth to do this.  Learned a lot from this project.  Good luck.

**Pull request closed without merging**
