### PR TITLE
Update House committee membership using House XML data

### PR DESCRIPTION
**Pull request by joelcollinsdc**
Probably some review needed here, especially around subcommittees and joint committee handling.  Refs #276

```
committee_membership_sanity_check.py
HLIG    : 22
 HLIG01 : 10
 HLIG02 : 10
 HLIG03 : 10
 HLIG04 : 10
HSAG    : 46
HSAP    : 52
HSAS    : 62
HSBA    : 60
HSBU    : 33
HSED    : 39
HSFA    : 47
HSGO    : 38
 HSGO06 : 9
 HSGO24 : 14
 HSGO25 : 8
 HSGO27 : 10
 HSGO28 : 6
 HSGO29 : 8
HSHA    : 9
HSHM    : 30
HSIF    : 55
 HSIF02 : 17
 HSIF03 : 31
 HSIF14 : 31
 HSIF16 : 29
 HSIF17 : 22
 HSIF18 : 22
HSII    : 42
HSJU    : 41
 HSJU01 : 13
 HSJU03 : 26
 HSJU05 : 13
 HSJU08 : 17
 HSJU10 : 8
HSPW    : 61
 HSPW02 : 30
 HSPW05 : 37
 HSPW07 : 14
 HSPW12 : 48
 HSPW13 : 13
 HSPW14 : 32
HSRU    : 13
HSSM    : 18
 HSSM23 : 3
 HSSM24 : 4
 HSSM25 : 6
 HSSM26 : 6
 HSSM27 : 5
HSSO    : 9
HSSY    : 31
HSVR    : 21
 HSVR03 : 12
 HSVR08 : 8
 HSVR09 : 6
 HSVR10 : 9
HSWM    : 38
 HSWM01 : 11
 HSWM02 : 17
 HSWM03 : 11
 HSWM04 : 16
 HSWM05 : 15
 HSWM06 : 11
JCSE    : 13
JSEC    : 17
JSLC    : 9
JSPR    : 8
JSTX    : 9
SCNC    : 6
SLET    : 6
SLIA    : 15
SLIN    : 19
SPAG    : 17
SSAF    : 21
 SSAF13 : 0
 SSAF14 : 0
 SSAF15 : 0
 SSAF16 : 0
 SSAF17 : 0
SSAP    : 31
 SSAP01 : 13
 SSAP02 : 19
 SSAP08 : 7
 SSAP14 : 13
 SSAP16 : 18
 SSAP17 : 15
 SSAP18 : 20
 SSAP19 : 17
 SSAP20 : 16
 SSAP22 : 18
 SSAP23 : 11
 SSAP24 : 19
SSAS    : 27
 SSAS13 : 13
 SSAS14 : 15
 SSAS15 : 10
 SSAS16 : 12
 SSAS17 : 9
 SSAS20 : 11
 SSAS21 : 11
SSBK    : 23
 SSBK04 : 17
 SSBK05 : 11
 SSBK08 : 19
 SSBK09 : 13
 SSBK12 : 11
SSBU    : 23
SSCM    : 27
 SSCM01 : 0
 SSCM20 : 0
 SSCM22 : 0
 SSCM24 : 0
 SSCM25 : 0
 SSCM26 : 0
SSEG    : 23
 SSEG01 : 18
 SSEG03 : 18
 SSEG04 : 14
 SSEG07 : 14
SSEV    : 21
 SSEV08 : 0
 SSEV09 : 0
 SSEV10 : 0
 SSEV15 : 0
SSFI    : 26
 SSFI02 : 8
 SSFI10 : 19
 SSFI11 : 20
 SSFI12 : 16
 SSFI13 : 12
 SSFI14 : 3
SSFR    : 21
 SSFR01 : 11
 SSFR02 : 11
 SSFR06 : 11
 SSFR07 : 11
 SSFR09 : 11
 SSFR14 : 11
 SSFR15 : 11
SSGA    : 15
 SSGA01 : 11
 SSGA18 : 9
 SSGA19 : 11
SSHR    : 23
 SSHR09 : 15
 SSHR11 : 15
 SSHR12 : 19
SSJU    : 20
 SSJU01 : 9
 SSJU04 : 15
 SSJU21 : 9
 SSJU22 : 9
 SSJU23 : 11
 SSJU25 : 15
SSRA    : 19
SSSB    : 19
SSVA    : 15
There are 157 total entries, 47 committees and 110 subcommittees.
```

### CODE REVIEW

**Comment by konklone** [comment]
cc @danielschuman - Would you be up for :eyes:-ing this?

**Comment by dwillis** [comment]
I did a couple of spot checks of committee membership totals and the script seems to have parsed the House Clerk's XML correctly, but the House Clerk's site seems to have some differences.  [House Budget](http://clerk.house.gov/committee_info/index.aspx?comcode=BU00) has 35 memberships currently while XML has 33.

**Comment by DanielSchuman** [comment]
Could it be that not everyone has been named to the committees yet? Happy
to check although Derek seems to have it in hand?

**Comment by joelcollinsdc** [comment]
Weird.  Looks like there are 35 in the clerk XML now, even though the last updated date is still 2/10.  The senate's site is throwing a 404 for some of the XML's now, I'll run it again tomorrow and see...

**Comment by joelcollinsdc** [comment]
Re-ran the script...

```
diff /tmp/before.txt /tmp/after.txt
< HSAS    : 62
---
> HSAS    : 61
11c10
< HSBU    : 33
---
> HSBU    : 35
14c13
< HSGO    : 38
---
> HSGO    : 41
22a22,27
>  HSHM05 : 8
>  HSHM07 : 8
>  HSHM08 : 11
>  HSHM09 : 8
>  HSHM11 : 12
>  HSHM12 : 8
30c35,40
< HSII    : 42
---
> HSII    : 43
>  HSII06 : 21
>  HSII10 : 21
>  HSII13 : 19
>  HSII15 : 11
>  HSII24 : 14
32,33c42,43
<  HSJU01 : 13
<  HSJU03 : 26
---
>  HSJU01 : 12
>  HSJU03 : 25
45c55
< HSSM    : 18
---
> HSSM    : 21
52,53c62,68
< HSSY    : 31
< HSVR    : 21
---
> HSSY    : 38
>  HSSY15 : 9
>  HSSY16 : 14
>  HSSY18 : 10
>  HSSY20 : 11
>  HSSY21 : 7
> HSVR    : 24
55,56c70,71
<  HSVR08 : 8
<  HSVR09 : 6
---
>  HSVR08 : 10
>  HSVR09 : 8
58c73
< HSWM    : 38
---
> HSWM    : 39
65,69c80,84
< JCSE    : 13
< JSEC    : 17
< JSLC    : 9
< JSPR    : 8
< JSTX    : 9
---
> JCSE    : 7
> JSEC    : 20
> JSLC    : 5
> JSPR    : 5
> JSTX    : 5
159c174
< There are 157 total entries, 47 committees and 110 subcommittees.
---
> There are 173 total entries, 47 committees and 126 subcommittees.
```

**Comment by JoshData** [comment]
How are we handling joint committees? I see it's TODO'd in the code.

(Also if we're not using the old scraper code anymore, let's delete the function.)

**Comment by joelcollinsdc** [comment]
thanks @konklone, cleaned those up and reran.

this is the changes from last time, some senate subcommittees got populated...

```
<  SSAF13 : 0
<  SSAF14 : 0
<  SSAF15 : 0
<  SSAF16 : 0
<  SSAF17 : 0
---
>  SSAF13 : 15
>  SSAF14 : 13
>  SSAF15 : 15
>  SSAF16 : 13
>  SSAF17 : 13
125,130c125,130
<  SSCM01 : 0
<  SSCM20 : 0
<  SSCM22 : 0
<  SSCM24 : 0
<  SSCM25 : 0
<  SSCM26 : 0
---
>  SSCM01 : 25
>  SSCM20 : 19
>  SSCM22 : 17
>  SSCM24 : 15
>  SSCM25 : 19
>  SSCM26 : 27
```

**Comment by joelcollinsdc** [comment]
I did some more cleanup, and changed sorting to be by chamber if its a joint committee.

I tried using the download function instead of requests but can't see to get it to do the encoding properly.  

-- name: Nanette Diaz Barragán
+- name: Nanette Diaz BarragÃ¡n

**Comment by joelcollinsdc** [comment]
I added a printout of what leadership roles were found for a committee to help with sanity checking.  There is probably some cleanup needed like house members saying 'chair' versus senate saying 'chairman'

```
HLIG    : 22 | Chair, Ranking Member
 HLIG01 : 10 | Chair, Ranking Member
 HLIG02 : 10 | Chair, Ranking Member
 HLIG03 : 10 | Chair, Ranking Member
 HLIG04 : 10 | Chair, Ranking Member
HSAG    : 46 | Chair, Ranking Member
HSAP    : 52 | Chair, Ranking Member
HSAS    : 61 | Chair, Ranking Member
HSBA    : 60 | Chair, Ranking Member
HSBU    : 35 | Chair, Ranking Member
HSED    : 39 | Chair, Ranking Member
HSFA    : 47 | Chair, Ranking Member
HSGO    : 41 | Chair, Ranking Member
 HSGO06 : 9  | Chair, Ranking Member
 HSGO24 : 14 | Chair, Ranking Member
 HSGO25 : 8  | Chair, Ranking Member
 HSGO27 : 10 | Chair, Ranking Member
 HSGO28 : 6  | Chair, Ranking Member
 HSGO29 : 8  | Chair, Ranking Member
HSHA    : 9  | Chair, Ranking Member
HSHM    : 30 | Chair, Ranking Member
 HSHM05 : 8  | Chair, Ranking Member
 HSHM07 : 8  | Chair, Ranking Member
 HSHM08 : 11 | Chair, Ranking Member
 HSHM09 : 8  | Chair, Ranking Member
 HSHM11 : 12 | Chair, Ranking Member
 HSHM12 : 8  | Chair, Ranking Member
HSIF    : 55 | Chair, Ranking Member
 HSIF02 : 17 | Chair, Ranking Member
 HSIF03 : 31 | Chair, Ranking Member
 HSIF14 : 31 | Chair, Ranking Member
 HSIF16 : 29 | Chair, Ranking Member
 HSIF17 : 22 | Chair, Ranking Member
 HSIF18 : 22 | Chair, Ranking Member
HSII    : 43 | Chair, Ranking Member
 HSII06 : 21 | Chair, Ranking Member
 HSII10 : 21 | Chair, Ranking Member
 HSII13 : 19 | Chair, Ranking Member
 HSII15 : 11 | Chair, Ranking Member
 HSII24 : 14 | Chair, Ranking Member
HSJU    : 41 | Chair, Ranking Member
 HSJU01 : 12 | Chair, Ranking Member
 HSJU03 : 25 | Chair, Ranking Member
 HSJU05 : 13 | Chair, Ranking Member
 HSJU08 : 17 | Chair, Ranking Member
 HSJU10 : 8  | Chair, Ranking Member
HSPW    : 61 | Chair, Ranking Member
 HSPW02 : 30 | Chair, Ranking Member
 HSPW05 : 37 | Chair, Ranking Member
 HSPW07 : 14 | Chair, Ranking Member
 HSPW12 : 48 | Chair, Ranking Member
 HSPW13 : 13 | Chair, Ranking Member
 HSPW14 : 32 | Chair, Ranking Member
HSRU    : 13 | Chair, Ranking Member
HSSM    : 21 | Chair, Ranking Member
 HSSM23 : 3  | Chair
 HSSM24 : 4  | Chair
 HSSM25 : 6  | Chair
 HSSM26 : 6  | Chair
 HSSM27 : 5  | Chair
HSSO    : 9  | Chair, Ranking Member
HSSY    : 38 | Chair, Ranking Member
 HSSY15 : 9  | Chair
 HSSY16 : 14 | Chair
 HSSY18 : 10 | Chair
 HSSY20 : 11 | Chair
 HSSY21 : 7  | Chair
HSVR    : 24 | Chair, Ranking Member
 HSVR03 : 12 | Chair, Ranking Member
 HSVR08 : 10 | Chair, Ranking Member
 HSVR09 : 8  | Chair, Ranking Member
 HSVR10 : 9  | Chair, Ranking Member
HSWM    : 39 | Chair, Ranking Member
 HSWM01 : 11 | Chair, Ranking Member
 HSWM02 : 17 | Chair, Ranking Member
 HSWM03 : 11 | Chair, Ranking Member
 HSWM04 : 16 | Chair, Ranking Member
 HSWM05 : 15 | Chair, Ranking Member
 HSWM06 : 11 | Chair, Ranking Member
JCSE    : 7  | Cochairman
JSEC    : 20 | Chair, Vice Chairman
JSLC    : 5  | Chairman
JSPR    : 5  | Vice Chairman
JSTX    : 5  | Vice Chairman
SCNC    : 6  | Chairman
SLET    : 6  | Chairman, Vice Chairman
SLIA    : 15 | Chairman, Vice Chairman
SLIN    : 19 | Chairman, Ex Officio, Ex Officio, Ex Officio, Ex Officio, Vice Chairman
SPAG    : 17 | Chairman, Ranking Member
SSAF    : 21 | Chairman, Ranking Member
 SSAF13 : 15 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSAF14 : 13 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSAF15 : 15 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSAF16 : 13 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSAF17 : 13 | Chairman, Ex Officio, Ex Officio, Ranking Member
SSAP    : 31 | Chairman
 SSAP01 : 13 | Chairman, Ranking Member
 SSAP02 : 19 | Chairman, Ranking Member
 SSAP08 : 7  | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSAP14 : 13 | Chairman, Ranking Member
 SSAP16 : 18 | Chairman, Ex Officio, Ranking Member
 SSAP17 : 15 | Chairman, Ranking Member
 SSAP18 : 20 | Chairman, Ex Officio, Ranking Member
 SSAP19 : 17 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSAP20 : 16 | Chairman, Ex Officio, Ranking Member
 SSAP22 : 18 | Chairman, Ex Officio, Ranking Member
 SSAP23 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSAP24 : 19 | Chairman, Ex Officio, Ex Officio, Ranking Member
SSAS    : 27 | Chairman, Ranking Member
 SSAS13 : 13 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSAS14 : 15 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSAS15 : 10 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSAS16 : 12 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSAS17 : 9  | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSAS20 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSAS21 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member
SSBK    : 23 | Chairman, Ranking Member
 SSBK04 : 17 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSBK05 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSBK08 : 19 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSBK09 : 13 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSBK12 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member
SSBU    : 23 | Chairman, Ranking Member
SSCM    : 27 | Chairman, Ranking Member
 SSCM01 : 25 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSCM20 : 19 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSCM22 : 17 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSCM24 : 15 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSCM25 : 19 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSCM26 : 27 | Chairman, Ex Officio, Ex Officio, Ranking Member
SSEG    : 23 | Chairman, Ranking Member
 SSEG01 : 18 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSEG03 : 18 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSEG04 : 14 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSEG07 : 14 | Chairman, Ex Officio, Ex Officio, Ranking Member
SSEV    : 21 | Chairman
 SSEV08 : 0  |
 SSEV09 : 0  |
 SSEV10 : 0  |
 SSEV15 : 0  |
SSFI    : 26 | Chairman, Ranking Member
 SSFI02 : 8  | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSFI10 : 19 | Chairman, Ex Officio, Ranking Member
 SSFI11 : 20 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSFI12 : 16 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSFI13 : 12 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSFI14 : 3  | Chairman, Ranking Member
SSFR    : 21 | Chairman, Ranking Member
 SSFR01 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSFR02 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSFR06 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSFR07 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member, Ranking Member
 SSFR09 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSFR14 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSFR15 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member
SSGA    : 15 | Chairman, Ranking Member
 SSGA01 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSGA18 : 9  | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSGA19 : 11 | Chairman, Ex Officio, Ex Officio, Ranking Member
SSHR    : 23 | Chairman, Ranking Member
 SSHR09 : 15 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSHR11 : 15 | Chairman, Ex Officio, Ex Officio, Ranking Member
 SSHR12 : 19 | Chairman, Ex Officio, Ex Officio, Ranking Member
SSJU    : 20 | Chairman, Ranking Member
 SSJU01 : 9  | Chairman, Ranking Member
 SSJU04 : 15 | Chairman, Ranking Member
 SSJU21 : 9  | Chairman, Ranking Member
 SSJU22 : 9  | Chairman, Ranking Member
 SSJU23 : 11 | Chairman, Ranking Member
 SSJU25 : 15 | Chairman, Ranking Member
SSRA    : 19 | Chairman, Chairman, Ranking Member
SSSB    : 19 | Chairman, Ranking Member
SSVA    : 15 | Chairman, Ranking Member
There are 173 total entries, 47 committees and 126 subcommittees.
```

**Comment by joelcollinsdc** [comment]
This still needs some work, it doesn't appear the clerk xml has Ex Officio members listed for some committees.  Its possible the xml publishing lags behind the website updating, but I'll try to reach out and ask.

The XML contains what it says on the website, Chairman / Chairwoman / Vice Chairman, while the current file contains Chair / Vice Chair.  Any concerns if we make the file match the website?

**Comment by DanielSchuman** [comment]
The House rules were updated a few years back to update chairman and
chairwoman should be changed to chair, etc.

**Comment by JoshData** [comment]
I have a preference for normalizing to gender-neutral terms, but I'm also ok either way. If the strings change I may need to make a corresponding change on GovTrack, fyi, but that's ok.

**Comment by joelcollinsdc** [comment]
Since the Clerk's site has a mix of Chair/Chairman/Chairwoman I thought it was the member's preference, like it is for Congressman/woman.

I reached out via the contact link on the clerk website about the ex oficio members being missing.  I compared the output of this with the master branch (needed to re-run in master branch since there are updates since 2 days ago) and the only differences i can find now are the ex oficio members.  So once this is resolved this should be good to go.

**Comment by joelcollinsdc** [comment]
I just realized that the subcommittees that are missing the ex-oficio members have this in their description: "The chairman and ranking minority member are ex officio members of all subcommittees".  Ugh.  So, I guess the XML is accurrate after all, i just need to account for this.

**Comment by DanielSchuman** [comment]
There's also a few unusual circumstances of ex-officio. For example, the
speaker and minority leader are ex-officio members of the House Intel
Committee. Don't know whether that's captured in the data, too.

**Comment by nschwamm** [comment]
I just want to add this here since Issue #455 was closed in reference to this issue. But there is a minor inconsistency relative to Vice Chairs. Currently there is "Vice Chair", "Vice Chairman", and "Vice-Chair"

**Comment by JoshData** [comment]
@dwillis ^

**Comment by JoshData** [comment]
I've brought this branch up to date and it is probably ready to merge.

For a while the House Clerk website was missing committee information and so the XML member data file (which this PR tried to switch us to four years ago) was the only way to update the data. While bringing this PR up to date, I realized that the House Clerk site's pages at https://clerk.house.gov/committees/AG00 started showing membership information, and we could have continued scraping, but this is probably better in the long run.

The only issue is that we're guessing that minority-party rank 1 members are Ranking Members, since this is not indicated in the XML.

The diff is large. Using `git show --minimal` on the command line reduces the noise by half.

**Pull request merged**
