### PR TITLE
Al Franken resigns effective 2018-01-02

### PR DESCRIPTION
**Pull request by bycoffe**
https://www.mprnews.org/story/2018/01/02/al-franken-resigns
http://www.startribune.com/transition-time-franken-moves-out-smith-moves-in/467678623/

### CODE REVIEW

**Comment by JoshData** [comment]
There are some extraneous changes in the committee files that are catching up for other changes it looks like. Otherwise lgtm, thanks.

On January 2, 2018 1:46:36 PM EST, Aaron Bycoffe <notifications@github.com> wrote:
>https://www.mprnews.org/story/2018/01/02/al-franken-resigns
>http://www.startribune.com/transition-time-franken-moves-out-smith-moves-in/467678623/
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/unitedstates/congress-legislators/pull/537
>
>-- Commit Summary --
>
>  * Al Franken resigns effective 2018-01-02
>
>-- File Changes --
>
>    M committee-membership-current.yaml (681)
>    M legislators-current.yaml (54)
>    M legislators-historical.yaml (54)
>
>-- Patch Links --
>
>https://github.com/unitedstates/congress-legislators/pull/537.patch
>https://github.com/unitedstates/congress-legislators/pull/537.diff
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/unitedstates/congress-legislators/pull/537

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bycoffe** [comment]
Should be taken care of now

**Comment by JoshData** [comment]
Something's still not quite right in the diff - something is going on with Conyers.

I can dive in later. We gotta also tee up Franken's replacement for tomorrow (happy to do it, I'd like to get it in tonight so GovTrack is up to date before I get on a flight tomorrow).

**Comment by bycoffe** [comment]
I'll just close this and open a new pull request

**Comment by bycoffe** [comment]
@JoshData these are the changes that will be needed for tomorrow, I think: https://github.com/bycoffe/congress-legislators/commit/56b2c10669d4e20c05d09d196dc6545049487ea8

That removes Luther Strange and adds Tina Smith and Doug Jones. It won't pass the validator right now because Strange's end date is in the future. Also Franken will need to be removed before Smith can be added.

**Pull request closed without merging**
