### PR TITLE
114th Congress updates

### PR DESCRIPTION
**Pull request by JoshData**
See #223.

### CODE REVIEW

**Comment by konklone** [comment]
The tests are failing because the `114th_congress.py` script loads a CSV that's not in version control. But the root issue is the script shouldn't execute simply by being imported (which is all the test script does). 

When I added the `workout` script, I also adjusted the other scripts to only execute when run directly. This means putting the bulk of the script inside of a function, e.g. `run()`, and then putting this at the bottom of the script:

```python
if __name__ == '__main__':
  run()
```

**Comment by JoshData** [comment]
It *is* in version control, actually. But thanks for fixing the script to not run. Travis still shows a failure.

**Comment by konklone** [comment]
There were two more scripts that needed a `run()` method to protect against execution-on-import. Added that, I suspect this Travis build will pass.

**Comment by konklone** [comment]
OK, build is fixed. It did throw a few pyflakes warnings (we add that in as an `after_success` command for Travis to run, but don't break the build on its failure) so I removed some unused imports and variables in cc0da3b. Build restored to pristine state. ;)

**Pull request merged**
