### PR TITLE
YouTube channel IDs for House and Senate committees, where applicable

### PR DESCRIPTION
**Pull request by ericisaiah**
I found these useful for a project and thought it would save others time if they were incorporated into the base repo.

Although legislators' social media accounts are in a separate yaml file, I suggest putting the committees' YouTube channel ID directly on the current committees list both for convenience and since it does not need to be updated with the same frequency as the legislators list.

Also worth noting that Senate committees largely do not have YouTube channels, but in cases where I could find those I added them, too.

### CODE REVIEW

**Comment by JoshData** [comment]
Would you also update README.md to document that this new field exists?

**Comment by ericisaiah** [comment]
Sure thing. I just added a line to the committee data dictionary, but let me know if you had something else in mind.

**Comment by JoshData** [comment]
Great, thank you!

**Comment by ericisaiah** [comment]
No problem. Thanks for maintaining this great resource.

**Pull request merged**
