### PR TITLE
district office updates

### PR DESCRIPTION
**Pull request by arrighik**
There are a lot of changes in here, but here's the list of sources (with the bioguide ids to make it a bit more digestible). Some of the changes were just stylistic (e.g. using "suite" instead of "ste." to make everything match.)

- A000055 : https://aderholt.house.gov/contact/offices
- A000367 : https://amash.house.gov/contact/offices
- A000374 : https://abraham.house.gov/contact/offices
- A000375 : https://arrington.house.gov/contact/offices
- B000574 : https://blumenauer.house.gov/contact/offices
- B000575 : https://www.blunt.senate.gov/public/index.cfm/office-locations
- B001236 : https://www.boozman.senate.gov/public/index.cfm/office-locations
- B001250 : https://robbishop.house.gov/
- B001251 : https://butterfield.house.gov/contact/offices
- B001260 : https://buchanan.house.gov/contact/offices
- B001261 : https://www.barrasso.senate.gov/public/index.cfm/office-locations
- B001275 : https://bucshon.house.gov/contact/offices
- B001277 : https://www.blumenthal.senate.gov/contact/
- B001285 : https://juliabrownley.house.gov/contact/offices
- B001286 : https://bustos.house.gov/
- B001291 : https://babin.house.gov/contact/officeinformation.htm
- B001294 : https://blum.house.gov/contact/officeinformation.htm
- B001295 : https://bost.house.gov/contact/offices/alton-office
- B001296 : https://boyle.house.gov/contact/offices
- B001297 : https://buck.house.gov/contact/offices
- B001300 : https://barragan.house.gov/contact/offices
- B001302 : https://biggs.house.gov/contact/offices/mesa-office
- B001304 : https://anthonybrown.house.gov/contact/offices
- B001305 : https://budd.house.gov/contact/officeinformation.htm
- C000141 : https://www.cardin.senate.gov/
- C000174 : https://www.carper.senate.gov/public/index.cfm/georgetown
- C000754 : https://cooper.house.gov/contact/offices
- C001037 : http://capuano.house.gov/contact/massachusetts.shtml
- C001038 : https://crowley.house.gov/office/bronx
- C001047 : https://www.capito.senate.gov/contact/office-locations
- C001056 : https://www.cornyn.senate.gov/contact
- C001062 : https://conaway.house.gov/contact/
- C001063 : https://cuellar.house.gov/
- C001071 : https://www.corker.senate.gov/public/
- C001078 : https://www.cassidy.senate.gov/contact/office-locations
- C001080 : https://chu.house.gov/contact/offices
- C001092 : https://chriscollins.house.gov/contact/offices
- C001093 : https://dougcollins.house.gov/contact-me/
- C001101 : http://katherineclark.house.gov/index.cfm/offices
- C001103 : https://comer.house.gov/contact
- C001109 : https://cheney.house.gov/about
- C001112 : https://carbajal.house.gov/contact/
- D000604 : https://dent.house.gov/index.cfm?p=berks-county-office
- D000610 : https://teddeutch.house.gov/district/officelocations.htm
- D000614 : https://duffy.house.gov/contact/offices
- D000615 : https://jeffduncan.house.gov/
- D000619 : https://rodneydavis.house.gov/
- D000621 : https://desantis.house.gov/offices
- D000623 : https://desaulnier.house.gov/contact/offices
- D000626 : https://davidson.house.gov/contact/offices
- E000285 : https://www.enzi.senate.gov/public/index.cfm/office-locations
- E000288 : https://ellison.house.gov/
- E000295 : https://www.ernst.senate.gov/public/index.cfm/office-locations
- F000062 : https://www.feinstein.senate.gov/public/index.cfm/state-offices
- F000457 : https://www.franken.senate.gov/
- G000289 : https://goodlatte.house.gov/
- G000359 : https://www.lgraham.senate.gov/public/
- G000386 : https://www.grassley.senate.gov/explore/regional-offices
- G000552 : https://gohmert.house.gov/contact/
- G000559 : https://garamendi.house.gov/
- G000562 : https://www.gardner.senate.gov/contact-cory/office-locations
- G000578 : https://gaetz.house.gov/contact/offices
- G000579 : https://gallagher.house.gov/contact/offices/green-bay
- G000580 : https://tomgarrett.house.gov/contact/offices
- G000581 : https://gonzalez.house.gov/contact/offices
- G000583 : https://gottheimer.house.gov/
- H000874 : https://hoyer.house.gov/contact-info/
- H001045 : https://harper.house.gov/
- H001046 : https://www.heinrich.senate.gov/contact/office-locations
- H001050 : https://hanabusa.house.gov/
- H001052 : https://harris.house.gov/
- H001056 : https://herrerabeutler.house.gov/
- H001058 : https://huizenga.house.gov/
- H001059 : https://hultgren.house.gov/contact/offices/mchenry-district-office
- H001061 : https://www.hoeven.senate.gov/
- H001064 : https://dennyheck.house.gov/
- H001065 : https://holding.house.gov/contact/officeinformation.htm
- H001067 : https://hudson.house.gov/my-office-locations/
- H001068 : https://huffman.house.gov/
- H001069 : https://www.heitkamp.senate.gov/public/index.cfm/contact
- H001072 : https://hill.house.gov/
- H001073 : https://hurd.house.gov/contact/offices
- H001074 : https://hollingsworth.house.gov/
- I000024 : https://www.inhofe.senate.gov/
- J000126 : https://ebjohnson.house.gov/
- J000289 : https://jordan.house.gov/district/office-hours.htm
- J000290 : https://lynnjenkins.house.gov/
- J000293 : https://www.ronjohnson.senate.gov/public/
- J000299 : https://mikejohnson.house.gov/
- K000188 : https://kind.house.gov/
- K000362 : https://steveking.house.gov/
- K000375 : https://keating.house.gov/
- K000378 : https://kinzinger.house.gov/
- K000380 : https://dankildee.house.gov/
- K000382 : https://kuster.house.gov/
- K000385 : https://robinkelly.house.gov/contact/offices/chicago-district-office
- K000386 : https://katko.house.gov/
- K000387 : https://knight.house.gov/
- K000390 : https://kihuen.house.gov/
- K000392 : https://kustoff.house.gov/
- L000287 : https://johnlewis.house.gov/
- L000480 : https://lowey.house.gov/
- L000551 : http://lee.house.gov/
- L000559 : https://langevin.house.gov/
- L000560 : https://larsen.house.gov/
- L000562 : https://lynch.house.gov/
- L000564 : https://lamborn.house.gov/
- L000567 : https://lance.house.gov/
- L000570 : https://lujan.house.gov/
- L000573 : https://labrador.house.gov/
- L000575 : https://www.lankford.senate.gov/contact/locations
- L000579 : https://lowenthal.house.gov/
- L000580 : https://lujangrisham.house.gov/
- L000585 : https://lahood.house.gov/
- M000087 : https://maloney.house.gov/
- M000133 : https://www.markey.senate.gov/office-locations
- M000303 : https://www.mccain.senate.gov/public/index.cfm/office-locations
- M000312 : https://mcgovern.house.gov/contact/
- M000355 : https://www.mcconnell.senate.gov/public/
- M000639 : https://www.menendez.senate.gov/contact/
- M000934 : https://www.moran.senate.gov/public/
- M001111 : https://www.murray.senate.gov/public/index.cfm/contactme
- M001137 : https://meeks.house.gov/
- M001143 : https://mccollum.house.gov/contact/offices/st-paul-office
- M001153 : https://www.murkowski.senate.gov/contact/office-locations
- M001156 : https://mchenry.house.gov/contact/
- M001166 : https://mcnerney.house.gov/contact/offices/do2city-district-office
- M001176 : https://www.merkley.senate.gov/connect/office-locations
- M001180 : https://mckinley.house.gov/
- M001181 : https://meehan.house.gov/
- M001187 : https://meadows.house.gov/contact/offices/county-offices
- M001188 : https://meng.house.gov/
- M001189 : https://messer.house.gov/
- M001190 : https://mullin.house.gov/
- M001193 : https://macarthur.house.gov/
- M001195 : https://mooney.house.gov/
- M001197 : https://mcsally.house.gov/
- M001198 : https://marshall.house.gov/contact/offices/garden-city-office-0
- M001199 : https://mast.house.gov/
- N000127 : https://nolan.house.gov/
- N000189 : https://newhouse.house.gov/
- O000168 : https://olson.house.gov/
- O000171 : https://ohalleran.house.gov/
- P000034 : https://pallone.house.gov/
- P000096 : https://pascrell.house.gov/
- P000258 : https://collinpeterson.house.gov/
- P000449 : https://www.portman.senate.gov/public/
- P000523 : https://price.house.gov/contact/offices
- P000588 : https://pearce.house.gov/
- P000595 : https://www.peters.senate.gov/contact/office-locations
- P000601 : https://palazzo.house.gov/
- P000603 : https://www.paul.senate.gov/connect/office-locations
- P000605 : https://perry.house.gov/
- P000606 : https://pittenger.house.gov/
- P000607 : https://pocan.house.gov/
- P000609 : https://palmer.house.gov/
- P000611 : https://poliquin.house.gov/
- P000612 : https://www.perdue.senate.gov/
- R000580 : https://roskam.house.gov/
- R000582 : https://roe.house.gov/
- R000585 : https://reed.house.gov/
- R000588 : https://richmond.house.gov/
- R000592 : https://rokita.house.gov/
- R000593 : https://dennisross.house.gov/
- R000595 : https://www.rubio.senate.gov/public/index.cfm/jacksonville-office
- R000598 : https://rothfus.house.gov/
- R000603 : https://rouzer.house.gov/
- R000606 : https://raskin.house.gov/
- R000607 : https://francisrooney.house.gov/district/interactivemap.htm
- S000033 : https://www.sanders.senate.gov/contact/
- S000320 : https://www.shelby.senate.gov/public/
- S000364 : https://shimkus.house.gov/
- S000480 : https://louise.house.gov/
- S000522 : https://chrissmith.house.gov/contact/
- S000583 : https://lamarsmith.house.gov/
- S000770 : https://www.stabenow.senate.gov/
- S001150 : http://schiff.house.gov/contact
- S001168 : https://sarbanes.house.gov/
- S001170 : https://shea-porter.house.gov/contact/offices/dover-office
- S001180 : https://schrader.house.gov/
- S001184 : https://www.scott.senate.gov/
- S001187 : https://stivers.house.gov/
- S001190 : https://schneider.house.gov/contact/offices
- S001197 : https://www.sasse.senate.gov/public/
- S001200 : https://soto.house.gov/
- S001201 : https://suozzi.house.gov/
- T000193 : https://benniethompson.house.gov/
- T000250 : https://www.thune.senate.gov/public/
- T000461 : https://www.toomey.senate.gov/
- T000464 : https://www.tester.senate.gov/?p=offices
- T000465 : https://tsongas.house.gov/
- T000468 : https://titus.house.gov/
- T000470 : https://tipton.house.gov/
- T000474 : https://torres.house.gov/
- T000476 : http://www.tillis.senate.gov/
- T000478 : https://tenney.house.gov/
- V000132 : https://vela.house.gov/
- W000437 : https://www.wicker.senate.gov/public/
- W000779 : https://www.wyden.senate.gov/
- W000795 : https://joewilson.house.gov/
- W000804 : https://wittman.house.gov/
- W000805 : https://www.warner.senate.gov/public/
- W000806 : https://webster.house.gov/
- W000808 : https://wilson.house.gov/
- W000819 : https://walker.house.gov/
- Y000033 : https://donyoung.house.gov/
- Y000062 : https://yarmuth.house.gov/
- Y000065 : https://yoho.house.gov/
- Y000066 : https://davidyoung.house.gov/
- Z000017 : https://zeldin.house.gov/
- H001075 : https://www.harris.senate.gov 
- Y000064 : https://www.young.senate.gov/
- D000622 : https://www.duckworth.senate.gov/
- H001076 : https://www.hassan.senate.gov/
- E000297 : https://espaillat.house.gov/
- T000477 : https://taylor.house.gov/
- V000128 : https://www.vanhollen.senate.gov/content/contact-senator
- K000393 : https://www.kennedy.senate.gov/public/office-information
- S001202 : https://www.strange.senate.gov/
- N000190 : https://norman.house.gov/

### CODE REVIEW

**Comment by JoshData** [comment]
We need someone to volunteer to lead reviewing PRs for the district office data....

**Comment by konklone** [comment]
@arrighik But before this gets merged, it does look like our YAML linter is flagging some issues:

https://travis-ci.org/unitedstates/congress-legislators/builds/317029976

It's a little hard to see without highlighting the diff lines there, but they seem to be about trailing spaces, and the occasional extra space between the `key:` and the `value`.

Mind cleaning those up? You can test whether you've fixed everything by running `pyflakes .` in the root of the project directory.

**Comment by jlev** [comment]
I linted this file and pushed to [my fork](https://github.com/jlev/congress-legislators/tree/lint-district-offices). Not sure if the new MN and AL senators will use the same district offices as their predecessors, so there's a minor merge conflict.

Want a clean PR, or shall I coordinate with @arrighik to push to their branch and update this one?

**Comment by woodhull** [comment]
Getting this sorted is way down in a long engineering backlog on our side so anything you can push across the finish line would be lovely. 

I promise it's on our card wall but no promises as to when we'll get to it otherwise if left to us to get to a mergeable state. :-/

**Comment by lavaturtle** [comment]
OK, I think we've finally got the lint issues and merge conflicts fixed. OK to merge now?

**Comment by konklone** [comment]
Thank you so much for doing this!

**Pull request merged**
