### PR TITLE
Scrape committee membership

### PR DESCRIPTION
**Pull request by JoshData**
Although @dwillis did a lot of work on manually collecting committee membership, there is a lot of new data and some errors. We have a scraper, but now that the data has membership start dates and links to sources, the scraper needed to be updated to preserve existing data in the file.

I updated the scraper. The result was a lot of changes. So I ran it in stages (full committees first, then (missing) subcommittees we didn't have, then subcommittees we already had) so we have at least one commit with a readable diff.

I also added the House Select Committee on the Climate Crisis and the House Select Committee on the Modernization of Congress to the metadata since they are on the Clerk site and have members.

### CODE REVIEW

**Comment by JoshData** [comment]
... I'm not sure how best to review this since one of the commits has a huge diff.

I think we also lost some _ex officiio_ entries which are indicated in source data @dwillis used but isn't in the clerk committee data.

**Comment by dwillis** [comment]
I can live with losing the Ex Officio members, tbh.

**Comment by dwillis** [comment]
@JoshData I'm in the process of reviewing these commits. Thanks for doing this!

**Comment by dwillis** [comment]
Here's a fun one: SSCM26, which has different information about the minority members in the [Senate XML](https://www.senate.gov/general/committee_membership/committee_memberships_SSCM.xml) vs. the [committee site](https://www.commerce.senate.gov/public/index.cfm/pressreleases?ID=928E144C-B9C8-478A-92B7-29C5B270ECA5).

**Comment by dwillis** [comment]
@JoshData I've done some clean-up on these files. Lemme know if that helps.

**Comment by JoshData** [comment]
Thanks. I'll take a look. I'm traveling this week and most of next so I'm not sure if I'll be able to look soon tho.

**Comment by dwillis** [comment]
@JoshData Any issues with this?

**Comment by JoshData** [comment]
Sorry, lost track, all good. Merging.

**Pull request merged**
