### PR TITLE
Official Twitter Accounts

### PR DESCRIPTION
**Pull request by putorti**
I'm both new to forking other repos in Github and to this repo, but hopefully this helps and I'll fix anything needed for next time.

### CODE REVIEW

**Comment by putorti** [comment]
I found a few other accounts but unclear still if they're official, official accounts:
- HawleyMO
- DustyJohnson

**Comment by putorti** [comment]
@konklone Okay I pulled Malinowski, just not sure how long you want to wait to merge the rest. If you want to merge right now, then remove, if you want to wait longer, then leave? Up to you guys.

**Comment by konklone** [comment]
@putorti Any interest in calling their offices? If not, I can do that tomorrow morning.

**Comment by putorti** [comment]
> @putorti Any interest in calling their offices? If not, I can do that tomorrow morning.

Sorry, I got the message in the car but if you don't beat me to it tomorrow morning, sure.

**Comment by putorti** [comment]
@konklone When do we think the branch will get merged?

**Comment by konklone** [comment]
@putorti it's merged! I merged it right after my last comment.

**Comment by csnardi** [comment]
@konklone It was merged into `116th_social`, not `master`, since @putorti changed the branch to merge into before #644 was merged. I think you'll need to make a PR then for merging `116th_social` into `master.

**Pull request merged**
