### PR TITLE
add curly apostrophes to O', D', L' names

### PR DESCRIPTION
**Pull request by JoshData**
O'Rourke => O’Rourke (curly single quote), and so on for O’Halleran and a bunch of other historical people

### CODE REVIEW

**Comment by bycoffe** [comment]
A few more names with apostrophes we might want to also change: `D'Alesandro`, `D'Ewart`, `D'Amato`, `L'Episcopo`, `D'Emory`, `D'Amours`, `L'Engle`.

**Comment by JoshData** [comment]
Got it. Updated the PR in-place. I used a script to update apostrophes in all `name:` fields.

**Comment by konklone** [comment]
Is this more grammatically correct in some way?

**Comment by JoshData** [comment]
It's the more correct glyph. Straight apostrophes aren't really a thing outside of coding.

**Pull request merged**
