### PR TITLE
Add district offices

### PR DESCRIPTION
**Pull request by tcarobruce**
This addresses #343 by making the following changes:

- adds the `legislators-district-offices.yaml` file
- documents the file and its fields in `README.md`
- extends `scripts/alternate_bulk_formats.py` to produce corresponding JSON and CSV files
- does validation of the district offices file using `scripts/office_validator.py`
- modifies `test/validate.py` to do office validation (for TravisCI/CircleCI)

The helper script used to do geocoding is also included. The push to gh-pages should work as well, though I'm unable to test that.

### CODE REVIEW

**Comment by JoshData** [comment]
Looks good to me. Thanks! Any other maintainers have thoughts?

I won't block a merge with these comments but just some data thoughts:

* It's normally a little cleaner to omit fields that have empty values, i.e. drop lines entirely whose values are the empty string.
* A more logical field order would make the data easier to read, e.g. id first, then all the address fields in the order they would appear on an envelope, then phone and fax, then longitude/latitude.

**Comment by tcarobruce** [comment]
I like both of these ideas, made the changes and added (non-error) checks to the validation script. Lat/lon are included after address since they're geographical.

**Comment by konklone** [comment]
@tcarobruce Thanks for the change! That looks good.

It looks like the district office validation script is in fact creating some build errors:
https://travis-ci.org/unitedstates/congress-legislators/builds/292335968

Any thoughts on those errors?

**Comment by tcarobruce** [comment]
Tim Murphy (M001151) resigned in the interim. I merged in the upstream change and removed his offices. Looks like it's working now!

Perhaps the office validator should suppress warnings when run under CI to make errors easier to find.

**Comment by konklone** [comment]
> Perhaps the office validator should suppress warnings when run under CI to make errors easier to find.

Yeah, that does sound good -- it appeared to be a deluge of errors at a quick glance.

But not a blocker for this PR, IMO. @JoshData, this is good with me if it's good with you.

**Comment by JoshData** [comment]
Looks good to me!

**Comment by konklone** [comment]
:tada:

**Pull request merged**
