### PR TITLE
Gregory F. Murphy has resigned from committees

### PR DESCRIPTION
**Pull request by syntheticgoo**
Ticket #807 .

This can be verified in the congressional record once posted for today: https://www.congress.gov/congressional-record/2022/01/25/daily-digest

### CODE REVIEW

**Comment by JoshData** [comment]
We use a script to maintain the committee membership files so this would be lost if we ran the script, which we should do since there are other updates. The easiest thing to do is wait for the change to appear in the clerk.house.gov data.

**Comment by JoshData** [comment]
It looks like he was moved to Ways and Means: https://www.govtrack.us/congress/bills/117/hres875/text

If you can add that to the PR, I'll merge it. Seems like the clerk.house.gov committee membership info is actually just out of date.

**Comment by GPHemsley** [comment]
It looks like running `committee_membership.py` will pick this change up now (along with a number of others), though it would revert #820 because Rep. Young's death hasn't been accounted for yet.

**Comment by JoshData** [comment]
Thanks. I ran the script and then sweep.py to remove legislators no longer serving (and pushed to main).

**Pull request closed without merging**
