### PR TITLE
Add Doug Jones, Tina Smith; retire Luther Strange

### PR DESCRIPTION
**Pull request by JoshData**
This PR is based on @bycoffe's commit bycoffe/congress-legislators@56b2c10 per #537.

I zapped Jones's and Smith's office/phone/contact_form fields since I'm not sure if they'll be the same as their predecessor? (Smith's contact_form had franken.senate.gov so I had to zap at least that.)

As @bycoffe mentioned it won't validate until tomorrow. Jones and Smith will be sworn in in the afternoon after the 2nd session starts, so I guess we could wait until the afternoon before merging. Or we could merge tonight ahead of time.

### CODE REVIEW

**Comment by JoshData** [comment]
Doug Jones has the wrong party. Will fix...

**Comment by bycoffe** [comment]
Thanks, sorry about that

**Comment by JoshData** [comment]
PR updated. Could someone review and merge?

**Comment by JoshData** [comment]
Oh, also- I changed Jones's name to Doug (vs Gordon Doug) because his FEC registration only used Doug and everyone knows him as Doug, so I think Doug fits better. That ok?

**Comment by bycoffe** [comment]
Fine with me.

**Pull request merged**
