### PR TITLE
add opensecrets IDs for Luther Strange and Ron Estes

### PR DESCRIPTION
**Pull request by mrumsky**

### CODE REVIEW

**Comment by JoshData** [comment]
Thanks. The tests failed because `scripts/generate_json.py` needs to be run to update the new JSON files too. Can you run that and push to update this PR?

**Comment by mrumsky** [comment]
Gotcha. I can't get it to work. Help? I'm on a Windows machine. I installed python and all the modules in scripts/requirements.txt. But when I run generate_json.py it changes something in the committee-membership-current.json file rather than in the legislators-current.json file, and I get an error.
```
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 326: character maps to <undefined>
```
Any ideas?

**Comment by JoshData** [comment]
Paging @joelcollinsdc and @konklone for help because they added the new JSON step. :-P

**Comment by joelcollinsdc** [comment]
@mrumsky is it easy to provide a stack trace?  I don't have a windows machine readily accessible to test with...

**Comment by joelcollinsdc** [comment]
Also, @JoshData  I'd say its not worth holding up this merge on the json stuff...

**Comment by mrumsky** [comment]
I was able to generate the json files successfully on a non-Windows machine. Before that, though, I merged more recent changes. Is that what caused the latest failed check?

**Comment by joelcollinsdc** [comment]
Thanks, and sorry.  I wonder if we have set some kind of record for the amount of time taken to review a 2 line addition to a YAML file.  I'd really like to move the JSON stuff out of this repo...   I am going to merge since the failing build seems to be something unrelated to this PR now.

**Pull request merged**
