### PR TITLE
update missing urls

### LINKED ISSUE #281: missing some committee urls
there are some committees in committees-current.yaml that now have urls . PR shortly.

--timball

### PR DESCRIPTION
**Pull request by timball**
some cmtes were missing urls . this fixes #281 .

--timball

### CODE REVIEW

**Comment by timball** [comment]
last commit fixes #283

--timball

**Comment by konklone** [comment]
This looks good to me. Note that it's creating a new field: `minority_url`. We had `url`, `rss_url`, and `minority_rss_url`, but we didn't have `minority_url`. Seems only helpful, assuming they're being used by _someone_. :)

**Comment by timball** [comment]
issue is that minority cmte offices are actual offices w/ like staff and fons and websites and addresses all the other associated jazz like that . the hack of just throwing in the "minority_url:" is a stopgap for me for a thing that i'm typing today .

a better thing would be to have a structure like :
```yaml
- type:
  name: 
  thomas_id: 
  house_committee_id:
  subcomittees:
  - # various subcomittee things
  office_of:
   - majority: # all associated data
   - minority: # all associated data
```

the pain is that congress does not maintain a contact repo like this that would be updated by a person who had duties to update it and ensure accuracy rather than me using the data and finding bugs .

--timball

**Comment by timball** [comment]
did this get merged ?

**Comment by konklone** [comment]
I rang in above with a :+1:, deferring to at least one other person for theirs. @JoshData ?

**Comment by JoshData** [comment]
Sorry for the delay, yes +1 wonderful thanks.

**Pull request merged**
