### PR TITLE
Add Tim Kaine Twitter

### PR DESCRIPTION
**Pull request by jaypinho**

### CODE REVIEW

**Comment by JoshData** [comment]
Hi. Thanks. This is his campaign account. As discussed in the README, we only add social media accounts that are run by the legislator's congressional office.

**Comment by jaypinho** [comment]
@JoshData @timkaine is his official account, I believe. @TeamKaine is his campaign account.

**Comment by JoshData** [comment]
How did you come to that conclusion?

**Comment by jaypinho** [comment]
@JoshData The @TeamKaine account bio says: "Official account for the grassroots team and volunteers working to re-elect @timkaine and the incredible Democratic ticket all across Virginia!" And it was only created 3 months ago. So that's the campaign one.

The @timkaine account has been around for 8 years and the bio says: "Husband to @AnneHolton, father of 3. U.S. Senator from Virginia. In my free time, I’m either outdoors, reading, or jamming on the harmonica." It contains generally the same type of material seen on other senators' official accounts as well.

**Comment by JoshData** [comment]
The easiest way to find out would be to call Kaine's Senate office and ask if they run the twitter account or not.

But I'm certain the answer is no. The give-away is that the account's profile links to https://timkaine.com/, which is a campaign website, and it would be a violation of Senate rules to do that on an official (i.e. government) twitter account.

**Comment by jaypinho** [comment]
Ah, good to know. Thanks!

**Pull request closed without merging**
