### PR TITLE
Lookup legislator properties by name and committee membership

### PR DESCRIPTION
**Pull request by essandess**
Add the ability to look up specific fields by committee membership or member last name. Wildcards are used. For example,

```
python congress_lookup.py -c 'Financ*' phone fax
```

prints the phone and fax numbers of all members of the **Senate Committee on Finance** and the **House Committee on Financial Services**.

The command

```
python congress_lookup.py -n Smith fax hours
```

prints all fax numbers and hours listed for any legislator named "Smith".

There are also a two database entry additions.

### CODE REVIEW

**Comment by konklone** [comment]
:+1: from me on this. However, it'd be nicer to have it in a separate directory from the data _gathering_ scripts.

It would be nice if the minor data updates (new fax number) were in a separate PR, but no big deal.

**Comment by essandess** [comment]
@konklone Thank you, I moved the lookup script out of the data *gathering* scripts.

And I must admit that single-file or single-commit PR's are a step beyond my git fu.

**Comment by essandess** [comment]
@JoshData 

1. My PR is intended to be the lookup script [congress_lookup.py](../../../essandess/congress-legislators/blob/master/congress_lookup.py). If that's acceptable, I'll lookup (or ask) how to submit this single file.

2. I see from [this commit](../../../unitedstates/congress-legislators/pull/405/commits/eb470385bfc45dd518a68b862864b0dafdd20fa2) that the Google APIs are used. If this is a TOS violation, then we should ask that OpenStreetMap be used instead.

3. The district office information is extremely important for contacting legislators, more than the DC offices:

https://www.ted.com/talks/omar_ahmad_political_change_with_pen_and_paper
http://www.nytimes.com/2016/11/22/us/politics/heres-why-you-should-call-not-email-your-legislators.html

I'm asking to find a way to include this important district office information. I use it myself, which is primarily why I wrote the lookup script originally.

**Comment by JoshData** [comment]
I'm fine with adding the lookup tool. (But not via the content of this PR.)

Let's keep the discussion about district data to #343.

**Comment by essandess** [comment]
I think I figured out out to cherry-pick the commits to submit a PR with just the lookup script and legislator-current updates. I'm going to close this PR and open a new one with the cherry-picked commits.

**Pull request closed without merging**
