### PR TITLE
added OpenSecrets ID for Darin LaHood

### PR DESCRIPTION
**Pull request by mrumsky**
http://www.opensecrets.org/politicians/summary.php?cid=N00037031&cycle=2016

### CODE REVIEW

**Comment by mrumsky** [comment]
added 5 FEC IDs from #332

**Comment by JoshData** [comment]
Are there any campaign finance experts watching this repo who can take the lead on reviewing PRs about the campaign finance fields?

**Comment by mrumsky** [comment]
I offer myself. :) We use many of those fields at MapLight, and I'm pretty familiar with both the structure of the "legislators-" files and the sources for the campaign finance-related IDs.

Regarding this particular PR, the CRP ID is pretty straightforward, and I checked that the five new FEC IDs did in fact belong to those legislators. I also checked for other Senators with no "S" FEC ID, and there aren't any others.

**Comment by JoshData** [comment]
Ok I've given you commit privs on this repo. :) Feel free to merge away!

**Comment by konklone** [comment]
Yes! My main request is to continue making PRs for all changes, and getting a :+1: on them is generally good. Definitely make branch-to-branch PRs within the repo though, which also lets other collaborators hop on the branch and make changes before merge in a smooth way.

**Comment by mrumsky** [comment]
Roger that, and thanks both of you. I'll follow that procedure for any future contributions.

**Pull request merged**
