### PR TITLE
Joint Committee on Taxation Membership

### PR DESCRIPTION
**Pull request by Panpog1**
Fixes issue #511

### CODE REVIEW

**Comment by JoshData** [comment]
Thanks. This only gets us part way there though. According to https://www.jct.gov/, Paul Ryan isn't on the committee, so we'd want to remove him, and if we can vet the rest of the membership while we're here that'd be great.

**Comment by Panpog1** [comment]
Members still need to be added. I'll look into that.

**Comment by Panpog1** [comment]
I removed nonmembers.

**Comment by JoshData** [comment]
HI there. So.... jct.gov now says Brady is the Vice Chair....

**Pull request closed without merging**
