### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by JoshData**

### CODE REVIEW

**Comment by chris-erickson** [comment]
Looks like these folks are sworn in now.

**Comment by chris-erickson** [comment]
Hey there, the recent build to generate the json failed.  The image does seem to exist, but must have been a transient fail.  Can we get this rerun?

https://app.circleci.com/pipelines/github/unitedstates/congress-legislators/35/workflows/dfefad86-45d5-408e-a01d-d9a4cae211c9/jobs/855/steps

https://hub.docker.com/layers/circleci/python/3.5-browsers/images/sha256-7eb805584a16f867a17b20ea6900f8e8d0623ec5ecaeed000b01e962180c7e8c?context=explore

**Comment by JoshData** [comment]
Ok should be good now. Thanks.

**Comment by chris-erickson** [comment]
Excellent, good on our end.

**Pull request merged**
