### PR TITLE
Fix last and middle name for Cathy McMorris Rodgers

### PR DESCRIPTION
**Pull request by asebold**

### CODE REVIEW

**Comment by JoshData** [comment]
That's how we used to have it, but it is not how she appears on House.gov anymore:

image

image

The switch from "McMorris Rodgers" to "Rodgers" as her last name appears to have happened in 2019 between roll calls 15 and 16.

**Comment by asebold** [comment]
Ugh, annoying. I reached out to the house.gov webmaster about it.

**Comment by GPHemsley** [comment]
@asebold Any luck?

(For the record, the screenshot above is of [https://www.house.gov/representatives#name-r](https://www.house.gov/representatives#name-r).)

**Comment by asebold** [comment]
@GPHemsley I remember reaching out to them but I don't believe I ever got a response.

**Comment by GPHemsley** [comment]
@asebold Well it looks to still be the case, so I doubt this was a mistake. Want to convert this to an `other_names` sections instead?

**Pull request merged**
